baseurl = "https://svenhofstede.com/"
title = "Sven Hofstede"
theme = "etch"
languageCode = "en-us"

[params]
  description = "Your site description"
  copyright = ""
  highlight = true
  dark = "off" 


[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

[permalinks]
  posts = "/:title/"